# Generated by Django 4.1 on 2024-01-03 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DateItem',
        ),
        migrations.DeleteModel(
            name='Statistics',
        ),
    ]
